version: '3.7'
services:
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./data/mongo-seed:/mongo-seed/
    command: /mongo-seed/mongoimport.sh

  api_server:
    build: ./Api
    ports:
      - "5000:5000"
    volumes:
      - ./data/images:/opt/data/images
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/animalhouse
      - JWT_SECRET=reallysecretpassword
      - NODE_ENV=production

  web:
    build: ./Clients
    ports:
      - "8000:80"
