version: '3.0'
services:
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /home/manuel/Scuola/UNI/2 Anno/2 Semestre/Tecnologie Web/Animal House - Progetto TW/Server/mongo-data:/data/db

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - /home/manuel/Scuola/UNI/2 Anno/2 Semestre/Tecnologie Web/Animal House - Progetto TW/Server/mongo-seed:/mongo-seed/
    command: 
      /mongo-seed/mongoimport.sh
