version: '3.0'
services:
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed/
    command: 
      /mongo-seed/mongoimport.sh
