version: '3.0'
services:
  mongo:
    restart: always
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - /run/media/manuel/HDD/Scuola/UNI/2 Anno/2 Semestre/Tecnologie Web/Animal House - Progetto TW/Server/mongo-data:/data/db