version: '3.0'
services:
  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  mongo_seed:
    image: mongo:latest
    links:
      - mongodb
    volumes:
      - C:\Users\andre\Desktop\UNI\2° anno\2° semestre\tecnologie\Animal-House_Progetto-TW\Server\mongo-seed:/mongo-seed/
    command: 
      /mongo-seed/mongoimport.sh
